Align Skeleton to skeleton/pose share code
nanit/deep-high-resolution-net.pytorch pull request #25
Opened 2022-02-17 15:53 UTC by tomer-algo

# Intro
  - Align Skeleton to skeleton/pose share code
# Project
  - Skeleton
  - Pose
# Implemented Sections
  - Use functions from code base s3://nanit-algo-resources/algo-infra/package-versions/nanit_algo_infra_online_additions-1.1.1-py3-none-any.whl
  - On which modules we can see the effect of the change - Utils Functions + Split
# Tests Description
  - Training
  - Split
  - Run Inference on TorchServe (local)
# Undeveloped Sections
  - 
# What's New
  - Using Code-base
# Checklist
  - [x] Module tested fully after last commit
  - [ ] Scheduled a PR meeting (if needed)
  - [ ] Documentation (comments or a dedicated document)
### Tested platforms
  - [x] Local
  - [ ] Cloud (SageMaker)
  - [ ] Staging
  - [ ] Not relevant
### Tested Cameras
  - [ ] Gen 1.5
  - [ ] Gen 2
  - [x] Not relevant
# Comments
### Included Features
  - 
### Infrastructure Dependencies
  - s3://nanit-algo-resources/algo-infra/package-versions/nanit_algo_infra_online_additions-1.1.1-py3-none-any.whl
### Tech Comments
  - 
### Testing Instructions
  - 
### Todos
  - 

![](https://nanit.com/favicon.ico)

2022-02-20 14:40 UTC, felixNan approved these changes

2022-02-21 12:42 UTC, Nimrods commented on analysis/analysis_utils.py
> -    os.environ['WANDB_DISABLE_CODE'] = '*.patch'
Did you change this command to the updated one W&B shared with Felix few months ago?
(in the shared code package I mean)

2022-02-21 12:42 UTC, Nimrods commented on export/config.properties
> +        "batchSize": 1,\
why just 1?
low throughput?

2022-02-21 12:45 UTC, Nimrods requested changes
Skeleton derived class shouldn't contain the base class same functionality only what's need to override

2022-02-21 13:52 UTC, tomer-algo commented on analysis/analysis_utils.py
> -    os.environ['WANDB_DISABLE_CODE'] = '*.patch'
using this function from `nanit-algo-infra-online-additions`
```
def init_wandb(project, notes, job_type):
    os.environ['WANDB_API_KEY'] = get_weights_and_biases_owner()
    wandb.init(project=project, notes=notes, job_type=job_type)

```

2022-02-21 13:52 UTC, tomer-algo commented on export/config.properties
> +        "batchSize": 1,\
low throughput, I aligned the code to the deployed model

2022-02-21 13:55 UTC, tomer-algo commented on skeleton_split/skeleton_split.py
> +class SkeletonSplitModule(SkeletonBaseSplitModule):
I didn't defined the functionality again, I've added another level in OOP
in  `nanit-algo-infra-online-additions` I have
`BaseSplitModule` -> `SkeletonBaseSplitModule`
for example in `SkeletonBaseSplitModule` I have additional method `parse_joints_from_skeleton_mark` that relevant only for "Skeleton Based" model

2022-02-22 06:45 UTC, Nimrods commented on analysis/analysis_utils.py
> -    os.environ['WANDB_DISABLE_CODE'] = '*.patch'
So we upload the code everytime, tnx

2022-02-22 06:46 UTC, Nimrods approved these changes

2022-02-22 07:47 UTC, merged